[package]
name = "finpass"
version = "1.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.1", features = ["derive"] }
rand = "0.8.5"

[[bin]]
name = "finpass"
path = "main.rs"
